apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --controller deployment
  #    --out k8s/
  #  kompose.version: 1.21.0 (992df58d8)
  #creationTimestamp: null
  labels:
    app.kubernetes.io/name: libraryapp
    app.kubernetes.io/component: {{ .Release.Name }}
#    io.kompose.service: gateway-server
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: http
  selector:
    app.kubernetes.io/name: libraryapp
    app.kubernetes.io/component: {{ .Release.Name }}
#    io.kompose.service: gateway-server
#status:
#  loadBalancer: {}
