# Use postgres/example user/password credentials
version: '3.1'

services:

  server:
    image: nitroshkin/service-gateway:${APP_VERSION}
    container_name: gateway
    expose:
     - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
   


