# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: nitroshkin/db-reservations:${APP_VERSION}
    container_name: reservations_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${RESERVATIONS_PG_PASSWORD}
      POSTGRES_USER: dev
      POSTGRES_DB: reservationservice
      PGDATA: /home/data
      POSTGRES_INITDB_ARGS: "-A md5"
    expose:
      - 5432
    ports:
      - "54321:5432"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data

  server:
    image: nitroshkin/service-reservations:${APP_VERSION}
    container_name: reservations
    expose:
     - 8070
    ports:
      - "8070:8070"
    depends_on:
      - db
    restart: unless-stopped
   
volumes:
  pg_data_volume:



