apiVersion: v1
kind: PersistentVolume
metadata:
  #creationTimestamp: null
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath: 
    path: /var/lib/postgresql/data
status: {}
