# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: nitroshkin/db-library:${APP_VERSION}
    container_name: library_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${LIBRARY_PG_PASSWORD}
      POSTGRES_USER: dev
      POSTGRES_DB: libraryservice
      PGDATA: /home/data
      POSTGRES_INITDB_ARGS: "-A md5"
    expose:
      - 5433
    ports:
      - "54322:5432"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data

  server:
    image: nitroshkin/service-library:${APP_VERSION}
    container_name: library
    expose:
     - 8060
    ports:
      - "8060:8060"
    depends_on:
      - db
    restart: unless-stopped
   
volumes:
  pg_data_volume:



